   var dependencies = {
    links:
      [
            { "source" : "BaseService", "dest" : "AFHTTPRequestOperationManager" },
            { "source" : "BaseService", "dest" : "AFJSONResponseSerializer" },
            { "source" : "BaseService", "dest" : "RACDisposable" },
            { "source" : "BaseService", "dest" : "RACSignal" },
            { "source" : "CPTTMService", "dest" : "BaseService" },
            { "source" : "DepartmentViewController", "dest" : "Department" },
            { "source" : "DepartmentViewController", "dest" : "RACCommand" },
            { "source" : "DepartmentViewController", "dest" : "RACSignal" },
            { "source" : "DepartmentViewController", "dest" : "TableViewController" },
            { "source" : "FaceBookService", "dest" : "BaseService" },
            { "source" : "main", "dest" : "AppDelegate" },
            { "source" : "NewsTableViewController", "dest" : "FaceBookService" },
            { "source" : "NewsTableViewController", "dest" : "News" },
            { "source" : "NewsTableViewController", "dest" : "TableViewController" },
            { "source" : "OfficeTableViewController", "dest" : "TableViewController" },
            { "source" : "TrainViewController", "dest" : "ViewController" },
            { "source" : "BaseService", "dest" : "AFHTTPRequestOperationManager" },
            { "source" : "BaseService", "dest" : "AFHTTPRequestSerializer" },
            { "source" : "BaseService", "dest" : "AFHTTPResponseSerializer" },
            { "source" : "BaseService", "dest" : "AFSecurityPolicy" },
            { "source" : "BaseService", "dest" : "AFNetworkReachabilityManager" },
            { "source" : "BaseService", "dest" : "RACSignal" },
            { "source" : "BaseService", "dest" : "RACDisposable" },
            { "source" : "BaseService", "dest" : "AFHTTPRequestOperation" },
            { "source" : "BaseService", "dest" : "RACDisposable" },
            { "source" : "CPTTMService", "dest" : "AFHTTPRequestOperationManager" },
            { "source" : "CPTTMService", "dest" : "AFHTTPRequestSerializer" },
            { "source" : "CPTTMService", "dest" : "AFHTTPResponseSerializer" },
            { "source" : "CPTTMService", "dest" : "AFSecurityPolicy" },
            { "source" : "CPTTMService", "dest" : "AFNetworkReachabilityManager" },
            { "source" : "DepartmentTableViewCell", "dest" : "RWLabel" },
            { "source" : "DepartmentViewController", "dest" : "DepartmentTableViewCell" },
            { "source" : "DepartmentViewController", "dest" : "RWLabel" },
            { "source" : "DepartmentViewController", "dest" : "RACSignal" },
            { "source" : "DepartmentViewController", "dest" : "Department" },
            { "source" : "DepartmentViewController", "dest" : "RACSignal" },
            { "source" : "FaceBookService", "dest" : "AFHTTPRequestOperationManager" },
            { "source" : "FaceBookService", "dest" : "AFHTTPRequestSerializer" },
            { "source" : "FaceBookService", "dest" : "AFHTTPResponseSerializer" },
            { "source" : "FaceBookService", "dest" : "AFSecurityPolicy" },
            { "source" : "FaceBookService", "dest" : "AFNetworkReachabilityManager" },
            { "source" : "FaceBookService", "dest" : "RACSignal" },
            { "source" : "NewsTableViewController", "dest" : "NewsTableViewCell" },
            { "source" : "NewsTableViewController", "dest" : "FaceBookService" },
            { "source" : "NewsTableViewController", "dest" : "AFHTTPRequestOperationManager" },
            { "source" : "NewsTableViewController", "dest" : "AFHTTPRequestSerializer" },
            { "source" : "NewsTableViewController", "dest" : "AFHTTPResponseSerializer" },
            { "source" : "NewsTableViewController", "dest" : "AFSecurityPolicy" },
            { "source" : "NewsTableViewController", "dest" : "AFNetworkReachabilityManager" },
            { "source" : "NewsTableViewController", "dest" : "RACCompoundDisposable" },
            { "source" : "NewsTableViewController", "dest" : "News" },
         ]
    }
  ;
